version: '3.1'

services:
  birdeye-auth:
    image: 'birdeye-auth'
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
