application:
  title: ${name}
  version: ${version}
  validate-mac: false
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/healthLedger
    username: birdeye
    password: birdeye
    initialization-mode: always
  jpa:
    open-in-view:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.subsel.healthledger.common.model.CustomPostgresDialect
  liquibase:
    changeLog: "classpath:db/migration/liquibase-changelog.yml"


server:
  port: 8080
  servlet:
    session:
      timeout: 300s
token:
  secret: "{bcrypt}$donald"
  expire: 180000
